#:schema node_modules/wrangler/config-schema.json
name = "bigbaby-sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e4ffcfcc234b4610ba581c02374ed84a" }
]
